version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ../Mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../Mosquitto/users:/mosquitto/config/users
      - ${DATA_DIR}/mosquitto/data:/mosquitto/data
      - ${DATA_DIR}/mosquitto/log:/mosquitto/log
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ${DATA_DIR}/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - ${DATA_DIR}/grafana:/var/lib/grafana
    restart: always

  generator:
    build: ../DataGenerator
    image: hskl-mti/generator
    container_name: generator
    depends_on:
      - mosquitto
    restart: always

  mqtt2influx:
    build: ../Mqtt2Influx
    image: hskl-mti/mqtt2influx
    container_name: mqtt2influx
    depends_on:
      - mosquitto
      - influxdb
      - grafana
    restart: always
